### ISSUE TITLE
what is the phase of the project？

### ISSUE THREAD

**Issue by woshilaiba** [hugefiver/qush#1]
Seems it is an attractive project！
can't wait to try it.

**Comment by hugefiver** [comment]
first, it actually **can be used**, but it only stop there at present.

it's a personal project, based on [this draft document](https://datatracker.ietf.org/doc/draft-bider-ssh-quic/)

as you can see, this project has a very simple functionality at this moment, which even cannot auth with system user platform. yes, its login auth is hard-coded in config file.

the capacity of one person is very limited, but i will continued work on it. And any contributions are welcome, even you can fork and work for yourself.

**Comment by Anthony-Hoo** [comment]
> first, it actually **can be used**, but it only stop there at present.
> 
> it's a personal project, based on [this draft document](https://datatracker.ietf.org/doc/draft-bider-ssh-quic/)
> 
> as you can see, this project has a very simple functionality at this moment, which even cannot auth with system user platform. yes, its login auth is hard-coded in config file.
> 
> the capacity of one person is very limited, but i will continued work on it. And any contributions are welcome, even you can fork and work for yourself.

we want see more functions of hugequicer, so gkd @hugefiver
