### ISSUE TITLE
Any benchmarks?

### ISSUE THREAD

**Issue by lonnietc** [hugefiver/qush#2]
Hello,

I really like the idea if using QUIC for SSH as my understanding is that QUIC is significantly faster that TCP based protocol in that it uses a reliable UDP protocol.

I was just wondering if you had any initial estimates on how fast QUSH is in comparison to SSH?
Thanks

**Comment by lonnietc** [comment]
I actually saw that you have some examples for comparison of qush/qushd and ssh/sshd which I was able to build but did not see any information on how to start any of them up for testing.

Can you please provide some information on this?
Thanks

**Comment by hugefiver** [comment]
Hi, I'm glad someone noticed this project. It was actually my undergraduate project and did include some test data in the final paper, but unfortunately that test data was lost. What I can tell you at this point is that SSH using QUSH transfers is 10% to -30% faster than the TCP version under some very aggressive parameters. The testing environment was using two VMware VMs with Linux's tc qdisc command to control latency and packet loss. I think it may be that the system kernel implementation is not optimized for UDP.
